name: Audit

on:
  pull_request:
    branches:
      - master
      - next
  schedule:
    - cron: '0 10 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Check Vulnerabilities
      run: npm audit --production --audit-level=moderate
