name: Changelog

on:
  pull_request:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check Changelog Updated
      id: checkchangelogupdated
      if: ${{ contains( github.event.pull_request.labels.*.name, 'no-changelog') != true }}
      uses: awharn/check_changelog_action@v1
      with:
        header: '## Recent Changes'
        file: 'CHANGELOG.md'
        lerna: true
        ignoreFiles: '__tests__|package.json|package-lock.json|*.md'
